"use client";
import type { ClayCalculation, ClayTestData } from "@/types";
import { DecimalInput } from "@/components/DecimalInput";
import { formatPt } from "@/lib/math";
export function ClayEditor({data,onChange,calculation}:{data:ClayTestData;onChange:(v:ClayTestData)=>void;calculation:ClayCalculation}){
  const patch=(i:number,key:"retainedPct"|"initialMassG"|"finalMassG"|"adoptedPct",value:number|null)=>onChange({intervals:data.intervals.map((d,j)=>j===i?{...d,[key]:value}:d)});
  const sum=data.intervals.reduce((a,r)=>a+(r.retainedPct??0),0);
  return <section className="test-editor"><div className="test-editor-title"><div><span className="step-chip">5</span><h3>Torrões de argila e materiais friáveis</h3></div><small>ABNT NBR 7218:2025 — cálculo por intervalo granulométrico e teor total.</small></div><div className="card">
    <div className="notice warn"><strong>Atenção:</strong> intervalos com menos de 5% da amostra podem ser dispensados do ensaio, mas continuam no cálculo com o teor adotado do intervalo vizinho conforme o procedimento.</div>
    <div className="table-wrap" style={{marginTop:12}}><table className="data"><thead><tr><th>Intervalo</th><th>% retida individual</th><th>Massa mínima (g)</th><th>mi (g)</th><th>mf (g)</th><th>Teor do intervalo (%)</th><th>Teor adotado se &lt;5%</th><th>Teor parcial (%)</th><th>Situação</th></tr></thead><tbody>{calculation.rows.map((r,i)=><tr key={r.key}><td><strong>{r.label}</strong></td><td><DecimalInput value={data.intervals[i]?.retainedPct} onValueChange={v=>patch(i,"retainedPct",v)}/></td><td>{formatPt(r.minimumMassG,0)}</td><td><DecimalInput disabled={(r.retainedPct??0)<5} value={data.intervals[i]?.initialMassG} onValueChange={v=>patch(i,"initialMassG",v)}/></td><td><DecimalInput disabled={(r.retainedPct??0)<5} value={data.intervals[i]?.finalMassG} onValueChange={v=>patch(i,"finalMassG",v)}/></td><td>{formatPt(r.clayPct,1)}</td><td><DecimalInput disabled={(r.retainedPct??0)>=5} value={data.intervals[i]?.adoptedPct} onValueChange={v=>patch(i,"adoptedPct",v)}/></td><td>{formatPt(r.partialPct,3)}</td><td><span className={`badge ${r.massStatus==="OK"||r.massStatus.startsWith("DISPENSADA")?"ok":r.massStatus==="MASSA INSUFICIENTE"?"bad":"warn"}`}>{r.massStatus}</span></td></tr>)}</tbody></table></div>
    <div className="result-cards"><div><small>Soma da composição</small><strong>{formatPt(sum,2)}%</strong></div><div><small>Teor total</small><strong>{formatPt(calculation.totalPct,3)}%</strong></div><div><small>Critério</small><strong>≤ 0,50%</strong></div><div><small>Status</small><strong className={calculation.overallStatus==="CONFORME"?"text-ok":calculation.overallStatus==="NÃO CONFORME"?"text-bad":""}>{calculation.overallStatus}</strong></div></div>
  </div></section>;
}
