"use client";
import type { PowderCalculation, PowderTestData } from "@/types";
import { DecimalInput } from "@/components/DecimalInput";
import { formatPt } from "@/lib/math";
export function PowderEditor({data,onChange,calculation}:{data:PowderTestData;onChange:(v:PowderTestData)=>void;calculation:PowderCalculation}){
  const patch=(i:number,key:"initialDryG"|"afterWashDryG",value:number|null)=>onChange({...data,determinations:data.determinations.map((d,j)=>j===i?{...d,[key]:value}:d) as PowderTestData["determinations"]});
  return <section className="test-editor"><div className="test-editor-title"><div><span className="step-chip">4</span><h3>Material pulverulento</h3></div><small>ABNT NBR 16973. Duas determinações e terceira quando necessária.</small></div><div className="card">
    <div className="form-grid"><div className="field c4"><label>Dimensão máxima nominal (mm)</label><DecimalInput value={data.nominalMaxSizeMm} onValueChange={v=>onChange({...data,nominalMaxSizeMm:v})}/></div><div className="field c4"><label>Tipo de agregado</label><select value={data.aggregateType} onChange={e=>onChange({...data,aggregateType:e.target.value as PowderTestData["aggregateType"]})}><option>GRAÚDO</option><option>MIÚDO</option></select></div><div className="field c4"><label>Massa mínima calculada</label><input value={`${formatPt(calculation.minimumMassG,0)} g`} readOnly/></div></div>
    <div className="table-wrap" style={{marginTop:14}}><table className="data"><thead><tr><th>Determinação</th><th>Massa seca inicial (g)</th><th>Massa após lavagem/seca (g)</th><th>Resultado (%)</th></tr></thead><tbody>{data.determinations.map((d,i)=><tr key={i}><td><strong>{i+1}ª {i===2?"(se necessária)":""}</strong></td><td><DecimalInput value={d.initialDryG} onValueChange={v=>patch(i,"initialDryG",v)}/></td><td><DecimalInput value={d.afterWashDryG} onValueChange={v=>patch(i,"afterWashDryG",v)}/></td><td>{formatPt(calculation.valuesPct[i]??null,3)}</td></tr>)}</tbody></table></div>
    <div className="result-cards"><div><small>Repetibilidade</small><strong>{calculation.repeatabilityStatus}</strong></div><div><small>Par adotado</small><strong>{calculation.adoptedPair||"—"}</strong></div><div><small>Resultado reportado</small><strong>{formatPt(calculation.reportedResultPct,1)}%</strong></div><div><small>Critério</small><strong>≤ 1,0%</strong></div><div><small>Status</small><strong className={calculation.overallStatus==="CONFORME"?"text-ok":calculation.overallStatus==="NÃO CONFORME"?"text-bad":""}>{calculation.overallStatus}</strong></div></div>
  </div></section>;
}
