import type { ReactNode } from "react";
import { COMPANY } from "@/config/company";
import { TRACK_BANDS } from "@/lib/granulometry";
import { TEST_CATALOG } from "@/lib/testCatalog";
import type { LabReportCalculation, LabReportData, TestType } from "@/types";
import { GranulometryChart } from "./GranulometryChart";

const f=(n:number|null|undefined,d=1)=>n==null?"—":n.toLocaleString("pt-BR",{minimumFractionDigits:d,maximumFractionDigits:d});
const datePt=(v:string)=>v?new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR"):"—";
const statusClass=(s:string)=>s==="CONFORME"?"r-ok":s==="NÃO CONFORME"?"r-bad":s.includes("PENDENTE")||s.includes("REPETIR")?"r-warn":"r-info";

function PageHeader({data,page,total,title}:{data:LabReportData;page:number;total:number;title:string}){
 const h=data.header;
 return <>
  <div className="rp-top"><img src="/logo-solocontrol.png" alt="Solocontrol"/><div><h1>RELATÓRIO DE ENSAIO - LASTRO FERROVIÁRIO</h1><p>{title}</p></div><div className="rp-doc"><strong>Relatório: {h.reportNumber||"—"} / Rev. {h.revision||"00"}</strong><span>Página {page} de {total}</span></div></div>
  <table className="rp-header"><tbody><tr><th>Interessado</th><td>{h.interested}</td><th>Data final</th><td>{datePt(h.completionDate)}</td></tr><tr><th>Obra</th><td>{h.work}</td><th>Amostra</th><td>{h.sample}</td></tr><tr><th>Procedência/Fornecedor</th><td>{h.supplierOrigin}</td><th>Material</th><td>{h.material}</td></tr><tr><th>Tipo/Designação</th><td>{h.sampleType||"—"}</td><th>Litologia</th><td>{h.lithology}</td></tr></tbody></table>
 </>;
}
function PageFooter({data}:{data:LabReportData}){const h=data.header;return <footer className="rp-footer"><div className="rp-foot-top"><div><strong>NOTAS:</strong><br/>1- {COMPANY.reportNotes[0]}<br/>2- {COMPANY.reportNotes[1]}</div><div className="rp-sign">________________________________<br/>RESPONSÁVEL PELO ENSAIO<br/><strong>{h.responsibleTechnician||"—"}</strong></div><div className="rp-sign">________________________________<br/>RESPONSÁVEL TÉCNICO<br/><strong>{h.technicalManager||"—"}</strong><br/>CREA: {h.crea||"—"}</div></div><div className="rp-company"><strong>{COMPANY.tradeName}</strong><br/>Fone: {COMPANY.phone} – E-mail: {COMPANY.email}<br/>{COMPANY.address}</div><div className="rp-prohibition">{COMPANY.footerNotice}</div></footer>}
function Page({data,page,total,title,children}:{data:LabReportData;page:number;total:number;title:string;children:ReactNode}){return <section className="report-a4 report-page"><PageHeader data={data} page={page} total={total} title={title}/><div className="rp-content">{children}</div><PageFooter data={data}/></section>}
function SectionTitle({children}:{children:ReactNode}){return <div className="rp-section-title">{children}</div>}

export function LabReport({data,calculation}:{data:LabReportData;calculation:LabReportCalculation}){
 const selected=new Set(data.selectedTests??[]); const pages:Array<(p:number,t:number)=>ReactNode>=[];
 if(selected.has("granulometria")&&calculation.granulometry){const c=calculation.granulometry;pages.push((p,t)=><Page key="gran" data={data} page={p} total={t} title="Composição granulométrica"><SectionTitle>1. GRANULOMETRIA • {TEST_CATALOG.granulometria.reference}</SectionTitle><table className="rp-table"><thead><tr><th>Peneira</th><th>mm</th><th>Peso A1 (g)</th><th>% ret. A1</th><th>Peso A2 (g)</th><th>% ret. A2</th><th>% passante</th><th>Faixa passante</th></tr></thead><tbody>{c.rows.map(r=><tr key={r.mm}><td>{r.label}</td><td>{f(r.mm,1)}</td><td>{f(r.retained1G,1)}</td><td>{f(r.retained1Pct,1)}</td><td>{f(r.retained2G,1)}</td><td>{f(r.retained2Pct,1)}</td><td>{f(r.passingPct,0)}</td><td>{100-r.maxRetainedAccum}–{100-r.minRetainedAccum}</td></tr>)}</tbody></table><div className="rp-result-row"><span>Massa inicial A1: <strong>{f(data.sample1MassG,1)} g</strong></span><span>Massa inicial A2: <strong>{f(data.sample2MassG,1)} g</strong></span><span>Status: <strong className={statusClass(c.overallStatus)}>{c.overallStatus}</strong></span></div><div className="rp-chart"><div className="rp-chart-label">CURVA GRANULOMÉTRICA • {TRACK_BANDS[data.band].label}</div><GranulometryChart band={data.band} calculation={c}/></div></Page>)}
 if(selected.has("forma")&&calculation.shape){
  const c=calculation.shape;
  const validRows=c.rows.filter(r=>r.classification!=="PENDENTE"&&r.aMm!==null&&r.bMm!==null&&r.cMm!==null);
  const fractions=Array.from(new Set(validRows.filter(r=>r.fractionMm!==null).map(r=>r.fractionMm as number))).sort((a,b)=>b-a);
  pages.push((p,t)=><Page key="shape" data={data} page={p} total={t} title="Índice de forma"><SectionTitle>2. ÍNDICE DE FORMA • {TEST_CATALOG.forma.reference}</SectionTitle>
    <div className="rp-kpis"><div><span>Fragmentos medidos</span><strong>{c.validCount}</strong></div><div><span>Média b/a</span><strong>{f(c.meanBA,2)}</strong></div><div><span>Média c/b</span><strong>{f(c.meanCB,2)}</strong></div><div><span>Forma média</span><strong>{c.meanClassification}</strong></div><div><span>Não cúbicas</span><strong>{f(c.nonCubicPct,1)}%</strong></div><div><span>Limite</span><strong>≤ {c.nonCubicLimitPct}%</strong></div></div>
    <table className="rp-table"><thead><tr><th>Fração</th><th>Nº fragmentos</th><th>Cúbicos</th><th>Alongados</th><th>Lamelares</th><th>Along.-lamelares</th><th>% não cúbicas</th></tr></thead><tbody>{fractions.map(fr=>{const rows=validRows.filter(r=>r.fractionMm===fr);const cub=rows.filter(r=>r.classification==="CÚBICA").length;const al=rows.filter(r=>r.classification==="ALONGADA").length;const la=rows.filter(r=>r.classification==="LAMELAR").length;const all=rows.filter(r=>r.classification==="ALONGADA LAMELAR").length;return <tr key={fr}><td>{f(fr,1)} mm</td><td>{rows.length}</td><td>{cub}</td><td>{al}</td><td>{la}</td><td>{all}</td><td>{rows.length?f(((rows.length-cub)/rows.length)*100,1):"—"}</td></tr>})}</tbody></table>
    <div className="rp-stat-grid"><div><span>Indicador</span><strong>b/a</strong><strong>c/b</strong></div><div><span>Média</span><strong>{f(c.meanBA,2)}</strong><strong>{f(c.meanCB,2)}</strong></div><div><span>Desvio-padrão</span><strong>{f(c.stdBA,3)}</strong><strong>{f(c.stdCB,3)}</strong></div><div><span>Coef. de variação</span><strong>{f(c.cvBA,1)}%</strong><strong>{f(c.cvCB,1)}%</strong></div></div>
    <div className="rp-box"><strong>Resultado da amostra:</strong> Forma média <strong>{c.meanClassification}</strong> • Partículas não cúbicas <strong>{f(c.nonCubicPct,1)}%</strong> • Situação <strong className={statusClass(c.overallStatus)}>{c.overallStatus}</strong>.</div>
    <div className="rp-note">As páginas seguintes apresentam as dimensões a, b e c, as relações b/a e c/b e a classificação individual de cada fragmento medido.</div>
  </Page>);

  const rowsPerPage=28;
  for(let start=0;start<validRows.length;start+=rowsPerPage){
    const group=validRows.slice(start,start+rowsPerPage);
    pages.push((p,t)=><Page key={`shape-detail-${start}`} data={data} page={p} total={t} title="Índice de forma — medições individuais"><SectionTitle>2.1 FRAGMENTOS MEDIDOS • DIMENSÕES E CLASSIFICAÇÃO INDIVIDUAL</SectionTitle>
      <table className="rp-table rp-shape-detail"><thead><tr><th>#</th><th>Fração (mm)</th><th>a (mm)</th><th>b (mm)</th><th>c (mm)</th><th>b/a</th><th>c/b</th><th>Classificação</th></tr></thead><tbody>{group.map((r,i)=><tr key={r.id}><td>{start+i+1}</td><td>{f(r.fractionMm,1)}</td><td>{f(r.aMm,1)}</td><td>{f(r.bMm,1)}</td><td>{f(r.cMm,1)}</td><td>{f(r.ba,1)}</td><td>{f(r.cb,1)}</td><td><strong>{r.classification}</strong></td></tr>)}</tbody></table>
      <div className="rp-note">Registro individual integrante do relatório de ensaio do índice de forma. Relações b/a e c/b classificadas conforme o método selecionado.</div>
    </Page>);
  }
 }
 if(selected.has("massa_especifica")&&calculation.physicalProperties){const c=calculation.physicalProperties;pages.push((p,t)=><Page key="phys" data={data} page={p} total={t} title="Massa específica, porosidade e absorção"><SectionTitle>3. PROPRIEDADES FÍSICAS • {TEST_CATALOG.massa_especifica.reference}</SectionTitle><table className="rp-table"><thead><tr><th>CP</th><th>Massa seca (g)</th><th>Massa saturada (g)</th><th>Massa submersa (g)</th><th>Massa específica (kg/m³)</th><th>Porosidade (%)</th><th>Absorção (%)</th></tr></thead><tbody>{c.rows.slice(0,14).map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{f(r.dryMassG,2)}</td><td>{f(r.saturatedMassG,2)}</td><td>{f(r.submergedMassG,2)}</td><td>{f(r.densityKgM3,0)}</td><td>{f(r.porosityPct,2)}</td><td>{f(r.absorptionPct,2)}</td></tr>)}</tbody></table><div className="rp-kpis"><div><span>Massa específica média</span><strong>{f(c.meanDensityKgM3,0)} kg/m³</strong><em>≥ {c.densityLimitKgM3}</em></div><div><span>Porosidade média</span><strong>{f(c.meanPorosityPct,2)}%</strong><em>≤ {c.porosityLimitPct}%</em></div><div><span>Absorção média</span><strong>{f(c.meanAbsorptionPct,2)}%</strong><em>≤ {c.absorptionLimitPct}%</em></div><div><span>Status</span><strong className={statusClass(c.overallStatus)}>{c.overallStatus}</strong></div></div></Page>)}
 if(selected.has("material_pulverulento")&&calculation.powder){const c=calculation.powder;pages.push((p,t)=><Page key="powder" data={data} page={p} total={t} title="Material pulverulento"><SectionTitle>4. MATERIAL PULVERULENTO • {TEST_CATALOG.material_pulverulento.reference}</SectionTitle><table className="rp-table"><thead><tr><th>Determinação</th><th>Massa seca inicial (g)</th><th>Massa após lavagem/seca (g)</th><th>Resultado (%)</th></tr></thead><tbody>{(data.powder?.determinations??[]).map((d,i)=><tr key={i}><td>{i+1}ª</td><td>{f(d.initialDryG,1)}</td><td>{f(d.afterWashDryG,1)}</td><td>{f(c.valuesPct[i],3)}</td></tr>)}</tbody></table><div className="rp-kpis"><div><span>Massa mínima</span><strong>{c.minimumMassG} g</strong></div><div><span>Repetibilidade</span><strong>{c.repeatabilityStatus}</strong></div><div><span>Resultado reportado</span><strong>{f(c.reportedResultPct,1)}%</strong></div><div><span>Critério</span><strong>≤ 1,0%</strong></div><div><span>Status</span><strong className={statusClass(c.overallStatus)}>{c.overallStatus}</strong></div></div></Page>)}
 if(selected.has("torroes_argila")&&calculation.clay){const c=calculation.clay;pages.push((p,t)=><Page key="clay" data={data} page={p} total={t} title="Torrões de argila e materiais friáveis"><SectionTitle>5. TORRÕES DE ARGILA E MATERIAIS FRIÁVEIS • {TEST_CATALOG.torroes_argila.reference}</SectionTitle><table className="rp-table"><thead><tr><th>Intervalo granulométrico</th><th>% retida</th><th>Massa mínima (g)</th><th>mi (g)</th><th>mf (g)</th><th>Teor intervalo (%)</th><th>Teor usado (%)</th><th>Teor parcial (%)</th></tr></thead><tbody>{c.rows.map(r=><tr key={r.key}><td>{r.label}</td><td>{f(r.retainedPct,1)}</td><td>{r.minimumMassG}</td><td>{f(r.initialMassG,1)}</td><td>{f(r.finalMassG,1)}</td><td>{f(r.clayPct,1)}</td><td>{f(r.usedPct,1)}</td><td>{f(r.partialPct,3)}</td></tr>)}</tbody></table><div className="rp-box"><strong>Teor total da amostra:</strong> {f(c.totalPct,3)}% • Critério ≤ 0,50% • <strong className={statusClass(c.overallStatus)}>{c.overallStatus}</strong>.</div></Page>)}
 const simpleTypes:TestType[]=["massa_unitaria","intemperie","los_angeles","treton","fragmentos_macios","micro_deval","point_load"];
 const simpleSummaries=calculation.summaries.filter(s=>simpleTypes.includes(s.type)); if(simpleSummaries.length){pages.push((p,t)=><Page key="other" data={data} page={p} total={t} title="Demais ensaios executados"><SectionTitle>6. DEMAIS ENSAIOS / RESULTADOS</SectionTitle><table className="rp-table matrix"><thead><tr><th>Ensaio</th><th>Resultado</th><th>Unidade</th><th>Critério / referência</th><th>Método</th><th>Situação</th></tr></thead><tbody>{simpleSummaries.map((s,i)=><tr key={`${s.type}-${i}`}><td>{s.label}</td><td>{s.result}</td><td>{s.unit}</td><td>{s.criterion}</td><td>{s.reference}</td><td className={statusClass(s.status)}><strong>{s.status}</strong></td></tr>)}</tbody></table><div className="rp-note">Os ensaios classificados como “REFERÊNCIA” são apresentados como informação técnica e não determinam isoladamente a rejeição do agregado.</div></Page>)}
 const photos=data.evidencePhotos??[]; for(let start=0;start<photos.length;start+=4){const group=photos.slice(start,start+4);pages.push((p,t)=><Page key={`photos-${start}`} data={data} page={p} total={t} title="Registro fotográfico"><SectionTitle>REGISTRO FOTOGRÁFICO / EVIDÊNCIAS</SectionTitle><div className="rp-photo-grid">{group.map((photo,i)=><figure key={`${photo.url}-${i}`}><img src={photo.url} alt={photo.caption||photo.name} crossOrigin="anonymous"/><figcaption>{photo.caption||photo.name}</figcaption></figure>)}</div>{data.header.latitude!=null&&<div className="rp-note">Geolocalização registrada na ficha: {data.header.latitude.toFixed(6)}, {data.header.longitude?.toFixed(6)}.</div>}</Page>)}
 pages.push((p,t)=><Page key="summary" data={data} page={p} total={t} title="Resumo de resultados e conclusão"><SectionTitle>RESUMO DOS ENSAIOS EXECUTADOS</SectionTitle><table className="rp-table matrix"><thead><tr><th>Característica</th><th>Resultado</th><th>Unidade</th><th>Critério</th><th>Referência</th><th>Situação</th></tr></thead><tbody>{calculation.summaries.map((s,i)=><tr key={`${s.type}-${i}`}><td>{s.label}</td><td>{s.result}</td><td>{s.unit}</td><td>{s.criterion}</td><td>{s.reference}</td><td className={statusClass(s.status)}><strong>{s.status}</strong></td></tr>)}</tbody></table><div className="rp-conclusion"><span>CONCLUSÃO DOS ENSAIOS SELECIONADOS</span><strong className={statusClass(calculation.overallStatus)}>{calculation.overallStatus}</strong></div>{data.header.latitude!=null&&<div className="rp-box"><strong>Geolocalização registrada:</strong> {data.header.latitude.toFixed(6)}, {data.header.longitude?.toFixed(6)} {data.header.locationCapturedAt?`• ${new Date(data.header.locationCapturedAt).toLocaleString("pt-BR")}`:""}</div>}<div className="rp-box"><strong>Observações:</strong> {data.header.observations||"Sem observações complementares."}</div></Page>);
 const total=pages.length; return <div id="official-report" className="report-document">{pages.map((render,i)=>render(i+1,total))}</div>;
}
